name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install buildozer
        run: |
          pip install buildozer cython==0.29.33
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip
      - name: Build APK
        run: buildozer android debug
      - uses: actions/upload-artifact@v3
        with:
          name: APK
          path: bin/*.apk
