name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: digreatbrian/buildozer-action@v2
        with:
          command: buildozer android debug
          buildozer_version: stable
      - uses: actions/upload-artifact@v4
        with:
          name: THEX-APK
          path: bin/*.apk
