name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Deps + FIX 37.0.0
        run: |
          sudo apt update
          sudo apt install -y aidl libffi-dev libssl-dev
          pip install cython==0.29.36 buildozer==1.5.0
          yes | sdkmanager --licenses
          sdkmanager "build-tools;37.0.0" "build-tools;33.0.2" "platforms;android-33" "platform-tools"
          sudo cp /usr/bin/aidl $ANDROID_HOME/build-tools/37.0.0/aidl || true
          sudo cp /usr/bin/aidl $ANDROID_HOME/build-tools/33.0.2/aidl || true
          sudo chmod +x $ANDROID_HOME/build-tools/37.0.0/aidl $ANDROID_HOME/build-tools/33.0.2/aidl || true
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/37.0.0
          cp -r $ANDROID_HOME/build-tools/37.0.0/* $HOME/.buildozer/android/platform/android-sdk/build-tools/37.0.0/ || true
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.2
          cp -r $ANDROID_HOME/build-tools/33.0.2/* $HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.2/ || true
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: THEX-APK
          path: bin/*.apk
