name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Build APK with Docker
        run: |
          sudo apt update
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer:master buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: THEX-APK
          path: bin/*.apk
